name: mad
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - torch
    - torchvision
    - absl-py==2.1.0
    - dm-control
    - termcolor==2.4.0
    - hydra-core==1.1.1
    - hydra-submitit-launcher==1.2.0
    - omegaconf==2.1.2
    - xmltodict==0.13.0
    - opencv-python
    - tb-nightly 
    - pandas 
    - pillow==10.2.0
    - moviepy==1.0.3
    - imageio==2.33.1
    - imageio-ffmpeg==0.4.9
    - wandb
    - kubernetes
    - transforms3d
    - sympy==1.13.1
    - setuptools==66
################### Metaworld requirements ################################
    - metaworld
################### ManiSkill requirements #####################################
    # - mani_skill